a = 34   
b = 6
print("a += b:",a + b)
print("a -= b:",a - b)
print(" *= b:", a * b)      
print("a/= b:", a / b)      
print("a %= b:", a % b)    
print("a **= b:", a ** b)      
print("a //= b:", a // b)